# Generated by Django 4.2.24 on 2025-10-31 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bracelet',
            name='badge',
            field=models.CharField(blank=True, choices=[('Modern Classic', 'Modern Classic'), ('Limited Edition', 'Limited Edition'), ('Bestseller', 'Bestseller')], default='Modern Classic', max_length=64),
        ),
        migrations.AddField(
            model_name='bracelet',
            name='category',
            field=models.CharField(choices=[('Bracelet', 'Bracelet'), ('Necklace', 'Necklace'), ('Ring', 'Ring'), ('Anklet', 'Anklet')], default='Bracelet', max_length=32),
        ),
        migrations.AddField(
            model_name='bracelet',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='bracelets/'),
        ),
        migrations.AddField(
            model_name='bracelet',
            name='is_signature_piece',
            field=models.BooleanField(default=False),
        ),
    ]
