# Generated by Django 4.2.24 on 2025-11-03 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_category_bracelet_category_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='bracelet',
            name='signature_category',
            field=models.CharField(blank=True, choices=[('fashion', 'Fashion Bracelets'), ('trending', 'Trending Bracelets'), ('latest', 'Latest Bracelet')], max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='bracelet',
            name='category',
            field=models.CharField(choices=[('Bracelet', 'Bracelet'), ('Necklace', 'Necklace')], default='Bracelet', max_length=32),
        ),
        migrations.AlterField(
            model_name='category',
            name='group',
            field=models.CharField(choices=[('bracelet', 'Bracelet'), ('chain', 'Chain')], default='bracelet', max_length=32),
        ),
    ]
