# Generated by Django 5.2.8 on 2025-11-11 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_bracelet_signature_category_alter_bracelet_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChainCategory',
            fields=[
            ],
            options={
                'verbose_name': 'Chain',
                'verbose_name_plural': 'Chains',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('store.category',),
        ),
        migrations.CreateModel(
            name='Chain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('imageUrl', models.URLField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='chains/')),
                ('category', models.CharField(choices=[('Chain', 'Chain'), ('Necklace', 'Necklace')], default='Chain', max_length=32)),
                ('badge', models.CharField(blank=True, choices=[('Modern Classic', 'Modern Classic'), ('Limited Edition', 'Limited Edition'), ('Bestseller', 'Bestseller')], default='Modern Classic', max_length=64)),
                ('is_signature_piece', models.BooleanField(default=False)),
                ('signature_category', models.CharField(blank=True, choices=[('fashion', 'Fashion Chains'), ('trending', 'Trending Chains'), ('latest', 'Latest Chain')], max_length=32, null=True)),
                ('category_ref', models.ForeignKey(blank=True, limit_choices_to={'group': 'chain'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chains', to='store.category')),
            ],
        ),
    ]
