# Generated by Django 4.2.24 on 2025-11-12 11:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_order_alter_chaincategory_options_bracelet_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BraceletSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('XS', 'Extra Small (5.5-6.0")'), ('S', 'Small (6.0-6.5")'), ('M', 'Medium (6.5-7.0")'), ('L', 'Large (7.0-7.5")'), ('XL', 'Extra Large (7.5-8.0")'), ('CUSTOM', 'Custom Size')], max_length=10, unique=True)),
                ('measurement_inches', models.CharField(blank=True, max_length=20, null=True)),
                ('price_modifier', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='ChainType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('base_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_available', models.BooleanField(default=True)),
                ('image_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomizationOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('option_type', models.CharField(choices=[('chain_type', 'Chain Type'), ('bead_type', 'Bead Type'), ('charm_type', 'Charm Type'), ('color', 'Color'), ('size', 'Size'), ('clasp_type', 'Clasp Type'), ('engraving', 'Engraving')], max_length=20)),
                ('product_type', models.CharField(choices=[('bracelet', 'Bracelet'), ('chain', 'Chain')], max_length=20)),
                ('price_modifier', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_available', models.BooleanField(default=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('metal', 'Metal'), ('bead', 'Bead'), ('charm', 'Charm'), ('chain', 'Chain'), ('clasp', 'Clasp')], max_length=50)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('price_modifier', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_available', models.BooleanField(default=True)),
                ('image_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomizedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(choices=[('bracelet', 'Bracelet'), ('chain', 'Chain')], max_length=20)),
                ('base_product_id', models.PositiveIntegerField(blank=True, null=True)),
                ('customization_data', models.JSONField()),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to='custom_previews/')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_saved', models.BooleanField(default=False)),
                ('cart_item', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.cartitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
