# Generated by Django 6.0.4 on 2026-06-05 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_wishlistitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bracelet',
            name='signature_category',
            field=models.CharField(blank=True, choices=[('fashion', 'Fashion'), ('trending', 'Trending'), ('latest', 'Latest'), ('none', 'General')], max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='chain',
            name='signature_category',
            field=models.CharField(blank=True, choices=[('fashion', 'Fashion'), ('trending', 'Trending'), ('latest', 'Latest'), ('none', 'General')], max_length=32, null=True),
        ),
    ]
